[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
